name: wecann
description: WeCan


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^8.3.0
  http: ^0.13.4
  geolocator: ^8.0.3
  qrscan: ^0.3.2
  mapmyindia_gl: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
